services:
  controller:
    build:
      context: ./controller
    volumes:
      - ./controller:/app
    working_dir: /app
    ports:
      - "8051:8051"
    command: python controller.py
    depends_on:
      - john
      - jane
      - james
  john:
    image: ghcr.io/cheqd/acapy-agent:py3.12-1.1.2-develop.3
    container_name: onlab-John-1
    ports:
      - "8031:8031"
    command: >
     start
      --label issuer
      --inbound-transport http 0.0.0.0 8031
     --outbound-transport http
     --admin 0.0.0.0 8030
     --admin-insecure-mode
     --endpoint http://john:8031
     --wallet-type askar
     --wallet-name issuer
     --wallet-key issuerkey
     --genesis-url https://raw.githubusercontent.com/cheqd/cheqd-node/main/networks/testnet/genesis.json
     --auto-provision
     --auto-accept-invites
     --auto-accept-requests

  jane:
    image: ghcr.io/cheqd/acapy-agent:py3.12-1.1.2-develop.3
    container_name: onlab-Jane-1
    ports:
      - "8032:8032"
    command: >
     start
     --label holder
      --inbound-transport http 0.0.0.0 8033
     --outbound-transport http
     --admin 0.0.0.0 8032
     --admin-insecure-mode
     --endpoint http://jane:8033
     --wallet-type askar
      --wallet-name holder
     --wallet-key holderkey
     --genesis-url https://raw.githubusercontent.com/cheqd/cheqd-node/main/networks/testnet/genesis.json
     --auto-provision
     --auto-accept-invites
      --auto-accept-requests

  james:
   image: ghcr.io/cheqd/acapy-agent:py3.12-1.1.2-develop.3
   container_name: onlab-James-1
   ports:
      - "8034:8034"
   command: >
     start
     --label verifier
     --inbound-transport http 0.0.0.0 8035
      --outbound-transport http
     --admin 0.0.0.0 8034
     --admin-insecure-mode
     --endpoint http://james:8035
     --wallet-type askar
     --wallet-name verifier
     --wallet-key verifierkey
     --genesis-url https://raw.githubusercontent.com/cheqd/cheqd-node/main/networks/testnet/genesis.json
     --auto-provision
     --auto-accept-invites
     --auto-accept-requests
