services:
  John:
    image: ghcr.io/hyperledger/aries-cloudagent-python:py3.9-0.12.6
    command: >
      start
      --inbound-transport http 0.0.0.0 8020
      --outbound-transport http
      --admin 0.0.0.0 8031
      --admin-insecure-mode
      --webhook-url http://controller:8051/webhooks
      --label John
      --wallet-type askar
      --wallet-name johnswallet
      --wallet-key johnskey123
      --auto-provision
      --auto-accept-invites
      --auto-respond-credential-offer
      --auto-respond-credential-request
      --auto-respond-presentation-request
      --auto-accept-requests
      --auto-ping-connection  
      --public-invites
      --no-ledger
      --endpoint http://john:8020
    ports:
      - "8020:8020"
      - "8031:8031"
    depends_on:
      - controller

  Jane:
    image: ghcr.io/hyperledger/aries-cloudagent-python:py3.9-0.12.6
    command: >
      start
      --inbound-transport http 0.0.0.0 8021
      --outbound-transport http
      --admin 0.0.0.0 8032
      --admin-insecure-mode
      --webhook-url http://controller:8051/webhooks
      --label Jane
      --wallet-type askar
      --wallet-name janeswallet
      --wallet-key janeskey123
      --auto-provision
      --auto-accept-invites
      --auto-respond-credential-offer
      --auto-respond-credential-request
      --auto-respond-presentation-request
      --auto-accept-requests
      --public-invites
      --auto-ping-connection
      --no-ledger
      --endpoint http://jane:8021
    ports:
      - "8021:8021"
      - "8032:8032"
    depends_on:
      - controller

  James:
    image: ghcr.io/hyperledger/aries-cloudagent-python:py3.9-0.12.6
    command: >
      start
      --inbound-transport http 0.0.0.0 8022
      --outbound-transport http
      --admin 0.0.0.0 8033
      --admin-insecure-mode
      --webhook-url http://controller:8051/webhooks
      --label James
      --wallet-type askar
      --wallet-name jameswallet
      --wallet-key jameskey123
      --auto-provision
      --auto-accept-invites
      --auto-respond-credential-offer
      --auto-respond-credential-request
      --auto-respond-presentation-request
      --auto-accept-requests
      --public-invites
      --auto-ping-connection
      --no-ledger
      --endpoint http://james:8023
    ports:
      - "8023:8023"
      - "8033:8033"
    depends_on:
      - controller

  controller:
    build:
      context: ./controller
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8051:8051"